# Part 1: goal definition 
geometry_msgs/Pose goal_pose
duration time_to_wait

---

# Part 2: result, sent by server upon completion
duration time_elapsed
bool     arrived_at_goal

---

# Part 3: feedback, to be sent periodically by the server

# amount of time that has elapsed from the start
duration time_elapsed

# amount of time remaining until finished
duration time_remaining