# X1 robot, sensor config 1
scan_topic: "/X1/front_scan"
# laser attributes, angle units are radians
angle_min: -2.35500001907
angle_max: 2.35500001907
angle_increment: 0.0475757569075

# number of measurements
num_measurements: 720

# laser range units are meters
range_min: 0.4
range_max: 5.0

distance_threshold: 1.0

# minimum gap between obstacles (should be scaled to robot's width)
min_gap: 1.2
